### ISSUE TITLE
Different result as expected

### ISSUE THREAD

**Issue by pieterwillaert** [Sleavely/Bark-JS#18]
Hi, 

When I use the library for this barcode 
`01054001414133413103000444` 

I suspect the expected result should contain 
`05400141413342` as GTIN part, 
but  I'm getting 
`05400141413341` 

I suspect something might be wrong calculating the check digit part:
https://www.gs1.org/services/check-digit-calculator

As you can see in this image the check-digit should be 2 instead of 1

![image](https://user-images.githubusercontent.com/1838822/115740282-f372c280-a38e-11eb-8d35-939fb502b081.png)

demo: https://runkit.com/embed/ar7qsm7nq3w0

**Comment by Sleavely** [comment]
Hi Pieter,

The way Bark is implemented it doesn't perform any validation or corrections of the data, it merely tries to categorize it. If you think auto-correcting the GTIN checkdigit would be a useful feature I'm mostly open to the idea; I'd love to better understand the usecase for it, since barcodes generally have similar mechanisms in place to protect against data corruption across the entirety of the barcode.
