### ISSUE TITLE
GS1 Barcode not being decoded properly.

### ISSUE THREAD

**Issue by lohchab** [Sleavely/Bark-JS#29]
@Sleavely Lot Code, Qty was not decoded properly for this GS1 Value.

let b = BarkJs('020002160010536011190801374100001234638')
console.log(b)

Giving this Output.

[
    {
        "ai": "02",
        "title": "CONTENT",
        "value": "00021600105360",
        "raw": "00021600105360"
    },
    {
        "ai": "11",
        "title": "PROD DATE",
        "value": "2019-08-01",
        "raw": "190801"
    },
    {
        "ai": "37",
        "title": "COUNT",
        "value": "41000012",
        "raw": "41000012"
    },
    {
        "ai": "3463",
        "title": "WIDTH (yd), log",
        "value": "0.8",
        "raw": "8"
    }
]

Here is the Original barcode for your reference.

![image](https://user-images.githubusercontent.com/6769716/174705903-188deda8-eb2d-4a93-94d1-3882c33bfb4a.png)

**Comment by Sleavely** [comment]
I think you may have stripped away invisible control characters while decoding the barcode. AI 37 (COUNT) requires an FNC1 marker to mark the end of the value because it does not have a fixed length (its `N2+N..8`), otherwise Bark will assume you are using the full length of the value which in this case means it's including the next identifier as part of its value.

This is usually something you can configure in your scanner, but unfortunately not something I can help with :(

**Comment by lohchab** [comment]
@Sleavely Thanks for pointing out. After using the Invisible Control Characters its working good. Thankyou for all your efforts and the work you are doing on this amazing library.

**Comment by lohchab** [comment]
The problem will happen when invisible control characters are not used in the Actual GS1 Barcode Value.
